project_name: "test_ChIP-seq"
project_dir: "~/projects/test_ChIP-seq"

## Aligner: bowtie or bowtie2
aligner: "bowtie"
pair_end: "yes"

## If use bowtie, then bowtie1 index path to be assigned here.
## "Genome" replaced by genome name as "hg19" or "mm9", and
## uncomment next line.
bowtie_index: "~/data/bowtie_index/Genome"

## If use bowtie2, then "Genome" should be replace by
## bowtie2 index name, as "hg19" or "mm9"
## $BOWTIE2_INDEXES should be added in the environment variables
# bowtie_index: "Genome"

bam_sort_buff: "2G"
IGV_genome: "hg19"
# ngsplot_genome: "reference_genome"
# ngsplot_fraglen: 150

## the folder under project folder, containing fastq folder.
data_dir: "data"

## match pattern for input files. Now it could be:
## *.fastq, *.fq, *.gz
## for pair end data, use "*R1*.fastq.gz" or "*R1*.fastq"
input_files: "*R1*.fastq.gz"

## cluster settings
cores: 4  # number of cores to use for multi-threaded programs.
queue: "queue_name"
h_vmem: "32G"

## wall_time for every step, hh:mm
wall_time:
    alignFastqByBowtie: "23:59"
    runFastqc: "4:00"
    rmdupBam: "20:00"
    genTDF: "20:00"
    runPhantomPeak: "20:00"
