project_name: "test_ChIP-seq"
project_dir: "~/projects/test_ChIP-seq"

## Aligner: bowtie or bowtie2
aligner: "bowtie"
pair_end: "no"

## If use bowtie, then bowtie1 index path to be assigned here.
## "Genome" replaced by genome name as "hg19" or "mm9", and
## uncomment next line.
bowtie_index: "~/data/bowtie_index/Genome"

## If use bowtie2, then "Genome" should be replace by
## bowtie2 index name, as "hg19" or "mm9"
## $BOWTIE2_INDEXES should be added in the environment variables
# bowtie_index: "Genome"

bam_sort_buff: "8G"
IGV_genome: "reference_genome"
# ngsplot_genome: "reference_genome"
# ngsplot_fraglen: 150

## the folder under project folder, containing fastq folder.
data_dir: "data"

## match pattern for input files. Now it could be:
## *.fastq, *.fq, *.gz
## for pair end data, use "*R1*.fastq.gz" or "*R1*.fastq"
input_files: "*.fastq"

## cluster settings
cores: 8  # number of cores to use for multi-threaded programs.
queue: "scavenger"  # scavenger is free. Use alloc or expressalloc for paid queues.
# m: "partition_to_run"  # by default, the cluster will choose a partition to run your job.
# alloc: "scavenger"  # use "acc_shenl03a" to use allocations.

## wall_time for every step, hh:mm
wall_time:
    alignFastqByBowtie: "23:59"
    runFastqc: "4:00"
    rmdupBam: "20:00"
    genTDF: "20:00"
    runPhantomPeak: "20:00"
